### ISSUE TITLE
servicenow.servicenow collection is deprecated

### ISSUE THREAD

**Issue by epicanthal** [ansible-community/ansible-build-data#144]
The servicenow.servicenow collection has been [deprecated](https://github.com/ServiceNowITOM/servicenow-ansible#readme).  Apologies if this is not the correct place to report this issue/info.  Possibly the original maintainers would want it as a candidate to be removed from future releases.

**Comment by mariolenz** [comment]
Thanks @epicanthal!

This has already been discussed in ansible-community/community-topics#44, but it looks like the deprecation problem has been kind of forgotten.

> Apologies if this is not the correct place to report this issue/info.

I'm not sure. Anyway, even if it's the wrong place: Thanks a lot for reminding us about this!
