### ISSUE TITLE
Ansible 6 is currently broken due to invalid collection dependencies

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/ansible-build-data#147]
community.mongodb 1.4.x depends on community.general < 5.0.0, but Ansible 6.1.0 contains both community.mongodb 1.4.1 and community.general 5.3.0.

I created https://github.com/ansible-collections/community.mongodb/issues/482 in the collection's repo.

**Comment by mariolenz** [comment]
Now that ansible-collections/community.mongodb#482 is closed and Ansible 6.2.0 released, is this still an open issue or can it be closed?

**Comment by felixfontein** [comment]
I just verified that there are no more invalid collection dependencies in Ansible 6.2.0. :tada:
