### ISSUE TITLE
[2023-04-26] Build 2nd Ansible 8 Alpha

### ISSUE THREAD

**Issue by samccann** [ansible-community/ansible-build-data#214]
Based on ansible-core RC1 (should be available on 4/24).

**Comment by samccann** [comment]
done

**Comment by gotmax23** [comment]
@felixfontein, as far as I can tell, the new version was used. I see `find_namespace_packages()` and the new `package_data` globs in the setup.py.

**Comment by felixfontein** [comment]
Hmm, looks like I downloaded the wrong tarball... yes, I can confirm that 8.0.0a1 was built with the correct version of antsibull. Sorry for the noise!

**Comment by gotmax23** [comment]
This should happen tomorrow, right?

**Comment by felixfontein** [comment]
@samccann 2013-05-02 would be the third alpha release according to the roadmap.

**Comment by samccann** [comment]
Okay I'll create a separate issue for that one. Meanwhile, we said in the Bullhorn that this one will happen on the 26th. Thanks for checking!

**Comment by samccann** [comment]
I didnt' add the dates when I created the issues. We do have a project board here that shows when items are due.

I'll add another issue for the 5/2 alpha.

**Comment by gotmax23** [comment]
I'd say so.
