### ISSUE TITLE
[2023-05-02] Build 3rd Ansible Alpha

### ISSUE THREAD

**Issue by samccann** [ansible-community/ansible-build-data#218]
Based on roadmap, this is due 5/2 with whatever is the most recent ansible-core 2.15 RC.

**Comment by samccann** [comment]
@gotmax23 I'm curious what you think of the project board here https://github.com/orgs/ansible-community/projects/7
Does that help? or do you still prefer dates in the titles instead?

**Comment by gotmax23** [comment]
I find that new projects interface quite confusing, and it doesn't work at all on mobile. I prefer to go to the issue tracker and at a glance see when the releases are expected. When I'm already in the ansible-build-data repository, it's just one click to the `Issues` tab.

**Comment by samccann** [comment]
makes sense, thanks for the explanation.

**Comment by anweshadas** [comment]
Released Ansible 8.0.0a3 today. 

- [Release notes](https://github.com/ansible-community/ansible-build-data/blob/main/8/CHANGELOG-v8.rst)

- [Ansible 8 Porting Guide](https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_8.html)
