### ISSUE TITLE
Build 7.5.1

### ISSUE THREAD

**Issue by jonathanspw** [ansible-community/ansible-build-data#232]
https://github.com/ansible-collections/ansible.posix/issues/451 is contained in the current posix collection version in 7.5.0 (1.5.2).

As this is a serious bug that could result in security vulnerabilities through bad firewalling I think it warrants a bump to 7.5.1 in which the posix module is updated.

**Comment by gotmax23** [comment]
I believe 7.6.0 is already planned for Tuesday. To begin with, I'm not sure the release manager has time to preform a release before then. Also, we don't currently have a policy in place to preform bugfix releases like this.

**Comment by gotmax23** [comment]
I filed https://github.com/ansible-community/community-topics/issues/231 to discuss further.

**Comment by felixfontein** [comment]
Considering that the new release of ansible.posix took a long time, I'm not sure it's worth rushing an Ansible release now that it finally got released, especially since there will be one in a few days anyway.

**Comment by felixfontein** [comment]
(While we're at it: ansible.posix doesn't conform to semver: https://github.com/ansible-collections/ansible.posix/issues/463)

**Comment by mariolenz** [comment]
@gotmax23 @felixfontein Feel free to re-open this issue if you think it necessary. Personally, I don't see the need for a 7.5.1 release when 7.6.0 will be released one or two days later, anyway.
