### ISSUE TITLE
Ansible 8 depclosure error in dellemc.enterprise_sonic

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/ansible-build-data#233]
```
ERROR: found collection dependency
ERROR: dellemc.enterprise_sonic version_conflict: ansible.netcommon-5.1.1 but needs >=2.0.0,<5.0.0
```

-- https://github.com/ansible-community/ansible-build-data/actions/runs/5029226827/jobs/9022214333?pr=227#step:9:367

https://github.com/ansible-collections/dellemc.enterprise_sonic/pull/176 is the offending change. We'll need to file an issue against the collection. This won't block the next Ansible 8 release, as we're in feature freeze, but this still needs to be addressed ASAP.

**Comment by felixfontein** [comment]
I created https://github.com/ansible-collections/dellemc.enterprise_sonic/issues/267.
