### ISSUE TITLE
[2023-09-26] Ansible 9.0.0 alpha1 

### ISSUE THREAD

**Issue by anweshadas** [ansible-community/ansible-build-data#256]
First alpha that picks up core 2.16 beta 1.

**Comment by anweshadas** [comment]
The ansible-core 2.16 Beta 1 release got postponed, created this issue to discuss on the ETA for Alpha1 https://github.com/ansible-community/community-topics/issues/276

**Comment by felixfontein** [comment]
Information on the 9.0.0a1 release here: https://github.com/ansible-community/ansible-build-data/issues/299#issuecomment-1739737647
