### ISSUE TITLE
Add servicenow.itsm as part of new community release

### ISSUE THREAD

**Issue by Akasurde** [ansible-community/ansible-build-data#268]
Since servicenow.servicenow collection has been deprecated by its maintainers and removed from Ansible 7. It is a good idea to include `servicenow.itsm`.

**Comment by Akasurde** [comment]
cc @tima

**Comment by felixfontein** [comment]
`servicenow.itsm` didn't apply for inclusion so far.

Related: https://github.com/ansible-community/community-topics/issues/44

**Comment by felixfontein** [comment]
Since there doesn't seem interest from servicenow.itsm's side to be included, I'll close this.
