### ISSUE TITLE
cyberark/conjur-ansible-collection

### ISSUE THREAD

**Issue by BradleyBoutcher** [ansible-community/ansible-build-data#28]
Per requirements for Ansible 2.10, the following link is the `CHANGELOG.md` for cyberark/conjur
https://github.com/cyberark/ansible-conjur-collection/blob/master/CHANGELOG.md

To further explain our format format, the CyberArk community and integrations team has an organization-wide policy for changelogs which follows both semantic versioning and [keepachangelog](https://keepachangelog.com/en/1.0.0/) formatting. This allows for the standardized validation of changelogs throughout all of our projects.

**Comment by felixfontein** [comment]
@BradleyBoutcher thanks for reporting the URL! It's now included in the changelog.
