### ISSUE TITLE
[2023-10-05+2]  Ansible9.0.0 alpha2 (if needed)

### ISSUE THREAD

**Issue by samccann** [ansible-community/ansible-build-data#295]
Optional release to pick up a second ansible-core 2.16 beta.

**Comment by anweshadas** [comment]
Updated the date in the issue from 2023-10-10 to 2023-10-05.

There has been a new ansible-core  2.16.0b2 release on 2023-10-03. 

But the package building was impacted by https://issues.redhat.com/browse/AAH-2738, which was resolved on 2023-10-04 with https://galaxy.ansible.com/ui/repo/published/vultr/cloud/?version=1.10.0.  

C arraying on the release on 2023-10-05.
