### ISSUE TITLE
Ansible 8/9 releases delayed

### ISSUE THREAD

**Issue by samccann** [ansible-community/ansible-build-data#302]
Building the package is impacted by https://issues.redhat.com/browse/AAH-2738.

We'll track progress on that for a  few days in hopes it gets resolved before we try any magic hoops to get around it.

**Comment by felixfontein** [comment]
Ansible 9 cannot currently be built since vultr.cloud 1.10.0 is missing from galaxy.ansible.com.

Ansible 8 can be built, but with an outdated vultr.cloud package (the last 8.4.0 release contained 1.9.0).

**Comment by rochacbruno** [comment]
Version 1.10.0 is there https://galaxy.ansible.com/ui/repo/published/vultr/cloud/?version=1.10.0 it was re-uploaded on the sync fix today.

**Comment by felixfontein** [comment]
@rochacbruno cool, thanks a lot! (https://github.com/ansible-community/antsibull/actions/runs/6375894954 now succeeds.)

BTW, 1.10.0 is not contained in the version drop-down, and in there 1.9.0 is still called "latest".

**Comment by felixfontein** [comment]
I guess this can be closed, as everything is fixed? Or did I miss something?

**Comment by samccann** [comment]
sorry about that, yeah afaik everything is working again so will close.
