### ISSUE TITLE
Fix Git tag failure on github workflow (for ansible release)

### ISSUE THREAD

**Issue by anweshadas** [ansible-community/ansible-build-data#376]
While running the github workflow for ansible-release the step for git tag failed, with the following error msg  : 

```
Run git config --global user.name "Github Actions"
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/ansible-build-data/ansible-build-data/ansible-build-data'. No such file or directory
```
https://github.com/ansible-community/ansible-build-data/actions/runs/8067689405/job/22044601494

**Comment by webknjaz** [comment]
Fixed by https://github.com/ansible-community/ansible-build-data/commit/d21223120bd7c7d08251e50c6168c06951cef759.
