### ISSUE TITLE
[2024-04-23] Release Ansible 9.5.0

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/ansible-build-data#385]
ansible-core 2.16.6 was released a week early. There was a setuptools change (https://setuptools.pypa.io/en/latest/history.html#v69-3-0, https://github.com/pypa/setuptools/pull/4286) that changed the way ansible-core dists (i.e., wheels and source distributions) that broke antsibull. Once we fix those issues and release new antsibull and antsibull-core releases, we can release Ansible 9.5.0.

**Comment by felixfontein** [comment]
I would suggest to wait with the 9.5.0 release until next week Tuesday (as originally scheduled) since several collection releases (community.general, community.dns, ...) are aligned with the Ansible release schedule.

**Comment by gotmax23** [comment]
Okay, makes sense to me

**Comment by gotmax23** [comment]
@felixfontein, @anweshadas, can I assign this to one of you? I will not be around next Tuesday, but I can probably do 9.6.0 if needed.

**Comment by felixfontein** [comment]
I have time next week, so I can do it. But if @anweshadas wants to do it that's also fine for me. Whatever you prefer @anweshadas :)

**Comment by anweshadas** [comment]
I do agree on doing the release as per our schedule. So let's stick  23rd April for 9.5.0 release.

**Comment by felixfontein** [comment]
9.5.1 is out now (replacing the mistakenly released and yanked 9.5.0 from yesterday).
