### ISSUE TITLE
ci: allow running release workflow from an existing branch

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/ansible-build-data#391]
This way, the release manager could commit other changes prior to running the release GHA while still having those changes included in the PR.

**Comment by felixfontein** [comment]
We might have to change antsibull as well so it only adds the release summary in case it isn't there already. Right now the prepare step always overwrites the release summary. (Which is the reason I'm doing 9.5.1 manually.)

**Comment by felixfontein** [comment]
Changes needed for antsibull:
- Do not clobber release summary and date when they're already present (or at least make that configurable);
- Allow to skip `prepare` step (`Prepare a release with new dependencies`) in the release role - this is needed for 10.0.0, which should have the exact same requirements as the last release candidate. Can also be needed in other cases.
- `Set up feature freeze for b2 through rc1` should be extended to more betas and also more release candidates (though likely for `rc2` and later RCs you want to use the feature from the previous bullet point, to explicitly force specific versions).

**Comment by felixfontein** [comment]
I created PRs for the antsibull features: https://github.com/ansible-community/antsibull/pull/597, https://github.com/ansible-community/antsibull/pull/598

**Comment by felixfontein** [comment]
#405 demonstrated that this now works :tada:
