### ISSUE TITLE
ci: make sure tag workflow tags the proper commit

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/ansible-build-data#401]
We should have the tag workflow query the Github API for the merged release PR's commit hash instead of just tagging the HEAD of the main branch.

**Comment by webknjaz** [comment]
It's possible to use GH CLI for this apparently:
* `--json`
* `--jq`
* https://github.com/cli/cli/issues/2306#issuecomment-1098748825
* https://cli.github.com/manual/gh_pr_view#options

**Comment by felixfontein** [comment]
I created #403 for this.

**Comment by felixfontein** [comment]
This also works: https://github.com/ansible-community/ansible-build-data/actions/runs/9079908048/job/24951174116 :tada:
