### ISSUE TITLE
Move GH workflow for nightly package builds to this repo

### ISSUE THREAD

**Issue by samccann** [ansible-community/ansible-build-data#417]
Currently the workflow that populates ansible-community/nightly-builds comes from https://github.com/ansible-community/antsibull/blob/main/.github/workflows/build-dumb-pypi.yml.

This (and other components of it, if they exist) should be moved to this repo.

Also consider if the 'nightly build' should happen more frequently than once a week :-)

**Comment by webknjaz** [comment]
I think it's not the right place — building things should happen where their sources exist. At least, in typical upstreams it works like this.
Downstream redistributors usually do this separately, of course: upstreams build and publish their dists to PyPI in own CIs within their own repositories, while RPM builds have separate specs in separate systems that fetch upstream artifacts and perform rebuilding.

Keeping the automation in the other repo also helps make sure that it remains healthy and if something breaks, the maintainers are actually notified. With a separate repo, no such notifications will ever reach the repo with sources.

**Comment by webknjaz** [comment]
This repository was meant to be a hosting for the static website and that's it.

Though, with the modern action-based GH Pages, it might make sense to move this hosting under that repo too.

**Comment by felixfontein** [comment]
@webknjaz this repo - ansible-build-data - is where the building of the Ansible community package happens. Notifications that the Ansible build broke should end up here, not in the repository of the build tool, which usually cannot do anything against it since the fixing needs to happen in this repo (usually adding build constraints until the source problem is fixed).

(Are you maybe confusing this repo with https://github.com/ansible-community/nightly-builds/ ?)

**Comment by felixfontein** [comment]
It's living in https://github.com/ansible-community/nightly-builds/ now, to simplify publishing the nightly builds there.

**Comment by felixfontein** [comment]
Moving that workflow here will a) change the URL of https://ansible-community.github.io/nightly-builds/ to https://ansible-community.github.io/ansible-build-data/ (which prevents us from using GH Pages for something else for this repo), b) add the burden of hosting these nightly builds to this repo (I have no idea if this is a problem or not).

**Comment by samccann** [comment]
Okay happy to close out this issue then if your satisfied on where things are now.

**Comment by felixfontein** [comment]
I'm happy with it, but I don't know what others think :)
