### ISSUE TITLE
Ansible 10.0.0 and Ansible 9.6.0 contain Windows binaries of unclear origin

### ISSUE THREAD

**Issue by leegarrett** [ansible-community/ansible-build-data#426]
In ansible community 10.0.0, there are several windows binaries being shipped of unclear origin:
```
$ find -name '*.exe'
./ansible_collections/kaytus/ksmanage/venv/Scripts/python.exe
./ansible_collections/kaytus/ksmanage/venv/Scripts/pip-3.7.exe
./ansible_collections/kaytus/ksmanage/venv/Scripts/wheel-3.7.exe
./ansible_collections/kaytus/ksmanage/venv/Scripts/pip3.7.exe
./ansible_collections/kaytus/ksmanage/venv/Scripts/pip.exe
./ansible_collections/kaytus/ksmanage/venv/Scripts/pythonw.exe
./ansible_collections/kaytus/ksmanage/venv/Scripts/pip3.exe
./ansible_collections/kaytus/ksmanage/venv/Scripts/wheel.exe
./ansible_collections/kaytus/ksmanage/venv/Scripts/wheel3.7.exe
./ansible_collections/kaytus/ksmanage/venv/Scripts/wheel3.exe
./ansible_collections/kaytus/ksmanage/venv/Lib/site-packages/pip/_vendor/distlib/t64.exe
./ansible_collections/kaytus/ksmanage/venv/Lib/site-packages/pip/_vendor/distlib/w32.exe
./ansible_collections/kaytus/ksmanage/venv/Lib/site-packages/pip/_vendor/distlib/w64.exe
./ansible_collections/kaytus/ksmanage/venv/Lib/site-packages/pip/_vendor/distlib/t32.exe
./ansible_collections/kaytus/ksmanage/venv/Lib/site-packages/setuptools/gui.exe
./ansible_collections/kaytus/ksmanage/venv/Lib/site-packages/setuptools/gui-64.exe
./ansible_collections/kaytus/ksmanage/venv/Lib/site-packages/setuptools/gui-32.exe
./ansible_collections/kaytus/ksmanage/venv/Lib/site-packages/setuptools/cli-64.exe
./ansible_collections/kaytus/ksmanage/venv/Lib/site-packages/setuptools/cli.exe
./ansible_collections/kaytus/ksmanage/venv/Lib/site-packages/setuptools/cli-32.exe
./ansible_collections/inspur/ispim/venv/Scripts/python.exe
./ansible_collections/inspur/ispim/venv/Scripts/pip-3.7.exe
./ansible_collections/inspur/ispim/venv/Scripts/wheel-3.7.exe
./ansible_collections/inspur/ispim/venv/Scripts/pip3.7.exe
./ansible_collections/inspur/ispim/venv/Scripts/pip.exe
./ansible_collections/inspur/ispim/venv/Scripts/pythonw.exe
./ansible_collections/inspur/ispim/venv/Scripts/pip3.exe
./ansible_collections/inspur/ispim/venv/Scripts/wheel.exe
./ansible_collections/inspur/ispim/venv/Scripts/wheel3.7.exe
./ansible_collections/inspur/ispim/venv/Scripts/wheel3.exe
./ansible_collections/inspur/ispim/venv/Lib/site-packages/pip/_vendor/distlib/t64.exe
./ansible_collections/inspur/ispim/venv/Lib/site-packages/pip/_vendor/distlib/w32.exe
./ansible_collections/inspur/ispim/venv/Lib/site-packages/pip/_vendor/distlib/w64.exe
./ansible_collections/inspur/ispim/venv/Lib/site-packages/pip/_vendor/distlib/t32.exe
./ansible_collections/inspur/ispim/venv/Lib/site-packages/setuptools/gui.exe
./ansible_collections/inspur/ispim/venv/Lib/site-packages/setuptools/gui-64.exe
./ansible_collections/inspur/ispim/venv/Lib/site-packages/setuptools/gui-32.exe
./ansible_collections/inspur/ispim/venv/Lib/site-packages/setuptools/cli-64.exe
./ansible_collections/inspur/ispim/venv/Lib/site-packages/setuptools/cli.exe
./ansible_collections/inspur/ispim/venv/Lib/site-packages/setuptools/cli-32.exe
```

This is a regression from 9.5.1, where this issue did not exist. Between those two releases kaytus 1.2.1 was added, and inspur.ispim was updated from 2.2.0 to 2.2.1. Would be nice to pin those to the previous state until the modules fixed their build process.

It looks like a whole venv is shipped with them, but I can't find those venv in the collection tarballs.

**Comment by leegarrett** [comment]
Yes, in my case I pull ansible from pypi, but galaxy will likely have the same problem. Would be nice to add a check for venv and .exe files in the ansible-community build process, though I'm not familiar with how ansible-community is built.

So the venv is in inspur/kaytus galaxy version (https://galaxy.ansible.com/ui/repo/published/kaytus/ksmanage/), however not in the tarballs directly published on github (https://github.com/ieisystem/kaytus.ksmanage/releases).

**Comment by mariolenz** [comment]
* [] ieisystem/kaytus.ksmanage#23
* [] ispim/inspur.ispim#35

**Comment by felixfontein** [comment]
The tarballs directly published on GH are auto-generated by GH from the repository, so the venv not being in there only means that they haven't been checked in. We're using the tarball from Galaxy. This is likely a failure during building the collection.

**Comment by felixfontein** [comment]
I pinged known maintainers/contributors of these collections and asked them to please create a new release without these files out ASAP, preferably this week so we can create 9.6.1 and 10.0.1 releases without them.

**Comment by baoshanwang** [comment]
inspur.ispim and kaytus.ksmanage have fixed the issues and released a new version, thanks!

**Comment by felixfontein** [comment]
@baoshanwang thank you very much, I checked both releases, they look good! kaytus.ksmanage also changed all line endings from CR+LF to LF, which is a good thing as well. I'll work on the releases now.

**Comment by felixfontein** [comment]
10.0.1 and 9.6.1 are out now without these files :tada:

**Comment by felixfontein** [comment]
10.0.0 and 9.6.0 have been yanked. Thanks everyone who helped resolving this, and thanks @leegarrett for reporting this!

**Comment by leegarrett** [comment]
Thanks everyone for the fast reponse!
