### ISSUE TITLE
Update community.aws to 1.3.0 for next Ansible 2.10.x release

### ISSUE THREAD

**Issue by artem-emelin** [ansible-community/ansible-build-data#46]
New community.aws 1.3.0 version fixes wrong element type for containers in ecs_taskdefinition:
https://github.com/ansible-collections/community.aws/pull/284

**Comment by felixfontein** [comment]
There's no need to create an issue like this. If a new version of community.aws has been released that satisfies the conditions (https://github.com/ansible-community/ansible-build-data/blob/main/2.10/ansible-2.10.build#L23 and is no pre-release), it will automatically be included in the next 2.10.x release.

**Comment by artem-emelin** [comment]
@felixfontein 
I see Ansible 2.10.5 contains the [fix](https://github.com/ansible-community/ansible-build-data/blob/main/2.10/CHANGELOG-v2.10.rst#changed-collections) so closing the issue.
Sorry for inconvenience if any.
