### ISSUE TITLE
Remove google.cloud from Ansible 12

### ISSUE THREAD

**Issue by gotmax23** [ansible-community/ansible-build-data#476]
https://forum.ansible.com/t/8609

**Comment by rpavlik** [comment]
It appears this is fixed? Kind of weird a vote for removal was somehow easier than just fixing the doc errors. https://github.com/ansible-collections/google.cloud/pull/655

**Comment by felixfontein** [comment]
It's not just about "docs errors". Also please use https://forum.ansible.com/t/8609 to discuss the removal, this issue is just for tracking the actual removal.
