### ISSUE TITLE
2.11 changelog

### ISSUE THREAD

**Issue by bendem** [ansible-community/ansible-build-data#67]
I've been looking everywhere and it looks like there just never was a changelog for 2.11, seeing as if this repo seems to contain automated changelogs, is there any reason why it's not included?

**Comment by felixfontein** [comment]
Ansible 2.11 does not exist, so there also was no changelog for it.

If you mean ansible-base 2.11, you can find it's changelog in the ansible repository: https://github.com/ansible/ansible/blob/stable-2.11/changelogs/CHANGELOG-v2.11.rst

**Comment by bendem** [comment]
Ah great, sorry for the noise then, I think I'm confused about how all those ansible parts fit together, why the versions are starting to diverge and which repo contain data related to which of those parts.
