### ISSUE TITLE
Create directory and test job for ansible 6

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ansible-build-data#83]
With Ansible 6 approaching, we need to create build and deps file for Ansible 6 -- we can target 6.0.0a1 for now.

We should probably take this opportunity to test with ansible devel (2.13 or the [milestone branch](https://github.com/ansible/ansible/tree/milestone)).

We can also test this ahead of time by copying the [existing job](https://github.com/ansible-community/ansible-build-data/blob/main/.github/workflows/antsibull-build.yml) and build 6.0.0a1 instead.

**Comment by Ompragash** [comment]
@dmsimard PR to add Ansible 6 build files: https://github.com/ansible-community/ansible-build-data/pull/90

**Comment by dmsimard** [comment]
PR merged, thanks @Ompragash !
